---
- name: Install Git
  hosts: jenkinsnew
  become: yes

  tasks:
    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Git
      package:
        name: git
        state: present
